# fly.toml file generated for bitter-sky-9233 on 2021-11-03T19:34:33-04:00

app = "bitter-sky-9233"

kill_signal = "SIGTERM"
kill_timeout = 5

[env]

[[services]]
  internal_port = 4000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "30s" # allow some time for startup
    interval = "15s"
    restart_limit = 6
    timeout = "2s"
